version: "3.8"
services:
  next-client:
    image: snowd3n/lucella:client
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
  node-server:
    image: snowd3n/lucella:server
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env
    ports:
      - 8080:8080
  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - POSTGRES_DB:${POSTGRES_DB}
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis:/data
volumes:
  postgres_data:
  redis:
