export enum TaskNames {
  deleteAllTestUsers = "deleteAllTestUsers",
  createCypressTestUser = "createCypressTestUser",
  connectSocket = "connectSocket",
  disconnectSocket = "disconnectSocket",
  disconnectAllSockets = "disconnectSoAllckets",
  socketEmit = "socketEmit",
  getUserEmail = "getUserEmail",
  getLastEmail = "getLastEmail",
  setRateLimiterDisabled = "setRateLimiterDisabled",
  setMaxConcurrentGames = "setMaxConcurrentGames",
  logUserIn = "logUserIn",
  logUserOut = "logUserOut",
  createSequentialEloTestUsers = "createSequentialEloTestUsers",
  putTwoSocketsInGameAndStartIt = "putTwoSocketsInGameAndStartIt",
  putTwoSocketClientsInRoomAndHaveBothReadyUp = "putTwoSocketClientsInRoomAndHaveBothReadyUp",
}
