export const newRoundStartingCountdownDuration = 5;
export const gameOverCountdownDuration = 2;
export const initialScoreNeededToWin = 5;
// export const baseSpeedModifier = 0.2;
export const baseSpeedModifier = 0.2; // 0.2
export const gameSpeedIncrementRate = 0.1; // 0.1
export const baseOrbRadius = 15;
export const orbMaxSpeed = 5;
export const decelerationDistance = 30;
export const orbDensity = 10;
export const frictionAir = 20.9;
export const initialEndZoneHeight = 60;
export const baseWindowDimensions = { width: 450, height: 750 };
export const orbWaypointListSizeLimit = 100;
export const orbsSpawnLocatioRightOffset = 75;
export const orbsSpawnSpacing = 50;
