export const gameOverCountdownDuration = 2;
export const initialScoreNeededToWin = 5;
export const baseSpeedModifier = 20;
export const gameSpeedIncrementRate = 1;
export const baseOrbRadius = 15;
export const orbDensity = 10;
export const frictionAir = 0.7;
export const initialEndZoneHeight = 60;
export const baseWindowDimensions = { width: 450, height: 750 };
