function convertGameStateIntoPacket({ gameState }) {
  const dateString = gameState.lastUpdateTimestamp.toString()
  const lastFourPlacesOfDateNow = parseInt(dateString.slice(dateString.length - 4))
  const packetArray = [
    gameState.lastProcessedCommandNumbers.host,
    gameState.lastProcessedCommandNumbers.challenger,
    gameState.orbs.hostOrbs[0].xPos,
    gameState.orbs.hostOrbs[0].yPos,
    gameState.orbs.hostOrbs[0].heading.xPos,
    gameState.orbs.hostOrbs[0].heading.yPos,
    gameState.orbs.hostOrbs[0].isGhost,
    gameState.orbs.hostOrbs[0].isSelected,
    gameState.orbs.hostOrbs[1].xPos,
    gameState.orbs.hostOrbs[1].yPos,
    gameState.orbs.hostOrbs[1].heading.xPos,
    gameState.orbs.hostOrbs[1].heading.yPos,
    gameState.orbs.hostOrbs[1].isGhost,
    gameState.orbs.hostOrbs[1].isSelected,
    gameState.orbs.hostOrbs[2].xPos,
    gameState.orbs.hostOrbs[2].yPos,
    gameState.orbs.hostOrbs[2].heading.xPos,
    gameState.orbs.hostOrbs[2].heading.yPos,
    gameState.orbs.hostOrbs[2].isGhost,
    gameState.orbs.hostOrbs[2].isSelected,
    gameState.orbs.hostOrbs[3].xPos,
    gameState.orbs.hostOrbs[3].yPos,
    gameState.orbs.hostOrbs[3].heading.xPos,
    gameState.orbs.hostOrbs[3].heading.yPos,
    gameState.orbs.hostOrbs[3].isGhost,
    gameState.orbs.hostOrbs[3].isSelected,
    gameState.orbs.hostOrbs[4].xPos,
    gameState.orbs.hostOrbs[4].yPos,
    gameState.orbs.hostOrbs[4].heading.xPos,
    gameState.orbs.hostOrbs[4].heading.yPos,
    gameState.orbs.hostOrbs[4].isGhost,
    gameState.orbs.hostOrbs[4].isSelected,
    gameState.orbs.challengerOrbs[0].xPos,
    gameState.orbs.challengerOrbs[0].yPos,
    gameState.orbs.challengerOrbs[0].heading.xPos,
    gameState.orbs.challengerOrbs[0].heading.yPos,
    gameState.orbs.challengerOrbs[0].isGhost,
    gameState.orbs.challengerOrbs[0].isSelected,
    gameState.orbs.challengerOrbs[1].xPos,
    gameState.orbs.challengerOrbs[1].yPos,
    gameState.orbs.challengerOrbs[1].heading.xPos,
    gameState.orbs.challengerOrbs[1].heading.yPos,
    gameState.orbs.challengerOrbs[1].isGhost,
    gameState.orbs.challengerOrbs[1].isSelected,
    gameState.orbs.challengerOrbs[2].xPos,
    gameState.orbs.challengerOrbs[2].yPos,
    gameState.orbs.challengerOrbs[2].heading.xPos,
    gameState.orbs.challengerOrbs[2].heading.yPos,
    gameState.orbs.challengerOrbs[2].isGhost,
    gameState.orbs.challengerOrbs[2].isSelected,
    gameState.orbs.challengerOrbs[3].xPos,
    gameState.orbs.challengerOrbs[3].yPos,
    gameState.orbs.challengerOrbs[3].heading.xPos,
    gameState.orbs.challengerOrbs[3].heading.yPos,
    gameState.orbs.challengerOrbs[3].isGhost,
    gameState.orbs.challengerOrbs[3].isSelected,
    gameState.orbs.challengerOrbs[4].xPos,
    gameState.orbs.challengerOrbs[4].yPos,
    gameState.orbs.challengerOrbs[4].heading.xPos,
    gameState.orbs.challengerOrbs[4].heading.yPos,
    gameState.orbs.challengerOrbs[4].isGhost,
    gameState.orbs.challengerOrbs[4].isSelected,
    gameState.score.host,
    gameState.score.challenger,
    gameState.score.neededToWin,
    lastFourPlacesOfDateNow,
    gameState.speed * 10,
  ];
  return new Int32Array(packetArray);
}

module.exports = convertGameStateIntoPacket;
