version: "3.8"
services:
  # toxiproxy:
  #   image: ghcr.io/shopify/toxiproxy
  #   ports:
  #     - "22220:22220"
  posgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # env_file:
    #   - .env
    environment:
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - POSTGRES_DB:${POSTGRES_DB}
    ports:
      - 5432:5432
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
volumes:
  postgres_data:
  redis:
