wandb_version: 1

exp_name:
  desc: null
  value: wandb_copied_ppo
gym_id:
  desc: null
  value: CartPole-v1
learning_rate:
  desc: null
  value: 0.00025
seed:
  desc: null
  value: 1
total_timesteps:
  desc: null
  value: 25000
torch_deterministic:
  desc: null
  value: true
cuda:
  desc: null
  value: true
track:
  desc: null
  value: true
wandb_project_name:
  desc: null
  value: ppo-implementation-details
wandb_entity:
  desc: null
  value: null
capture_video:
  desc: null
  value: true
num_envs:
  desc: null
  value: 4
num_steps:
  desc: null
  value: 128
anneal_lr:
  desc: null
  value: true
gae:
  desc: null
  value: true
gamma:
  desc: null
  value: 0.99
gae_lambda:
  desc: null
  value: 0.95
num_minibatches:
  desc: null
  value: 4
update_epochs:
  desc: null
  value: 4
norm_adv:
  desc: null
  value: true
clip_coef:
  desc: null
  value: 0.2
clip_vloss:
  desc: null
  value: true
ent_coef:
  desc: null
  value: 0.01
vf_coef:
  desc: null
  value: 0.5
max_grad_norm:
  desc: null
  value: 0.5
target_kl:
  desc: null
  value: null
batch_size:
  desc: null
  value: 512
minibatch_size:
  desc: null
  value: 128
_wandb:
  desc: null
  value:
    code_path: code/packages/server/battle-room-rl/Battle-Room-Environment/battle-room-enviroment/env/wandb_copied_ppo.py
    python_version: 3.10.10
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1685132071.737265
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      2:
      - 1
      - 2
      - 3
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.10.10
      5: 0.15.3
      8:
      - 5
