export enum GameStatus {
  IN_LOBBY = "IN_LOBBY",
  COUNTING_DOWN = "COUNTING_DOWN",
  IN_PROGRESS = "IN_PROGRESS",
  GAME_OVER_SCREEN = "GAME_OVER_SCREEN",
  ENDING = "ENDING",
}

export enum PlayerRole {
  HOST = "host",
  CHALLENGER = "challenger",
}

export enum UserInputs {
  MOVE_ORBS_TOWARD_DESTINATIONS = "MOVE_ORBS_TOWARD_DESTINATIONS",
  SELECT_ORBS = "SELECT_ORBS",
  ASSIGN_ORB_DESTINATIONS = "ASSIGN_ORB_DESTINATIONS",
  SELECT_ORB_AND_ASSIGN_DESTINATION = "SELECT_ORB_AND_ASSIGN_DESTINATION",
}
