name: Tests

on:
  pull_request:
    branches: [main]

env:
  SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
  NODE_ENV: ${{ secrets.NODE_ENV }}
  EMAIL_ROOT_URL: ${{ secrets.EMAIL_ROOT_URL }}
  EMAIL_ROOT_URL_DEV: ${{ secrets.EMAIL_ROOT_URL_DEV }}
  PORT: ${{ secrets.PORT }}
  ORIGIN: ${{ secrets.ORIGIN }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  REDIS_URL: ${{ secrets.REDIS_URL }}
  ACCESS_TOKEN_EXPIRES_IN: ${{ secrets.ACCESS_TOKEN_EXPIRES_IN }}
  AUTH_SESSION_EXPIRATION: ${{ secrets.AUTH_SESSION_EXPIRATION }}
  PASSWORD_RESET_TOKEN_EXPIRES_IN: ${{ secrets.PASSWORD_RESET_TOKEN_EXPIRES_IN }}
  ACCOUNT_ACTIVATION_SESSION_EXPIRATION: ${{ secrets.ACCOUNT_ACTIVATION_SESSION_EXPIRATION }}
  TESTER_KEY: ${{ secrets.TESTER_KEY }}
  CYPRESS_TEST_USER_NAME: ${{ secrets.CYPRESS_TEST_USER_NAME }}
  ACCESS_TOKEN_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN_PRIVATE_KEY }}
  ACCESS_TOKEN_PUBLIC_KEY: ${{ secrets.ACCESS_TOKEN_PUBLIC_KEY }}
  REFRESH_TOKEN_PRIVATE_KEY: ${{ secrets.REFRESH_TOKEN_PRIVATE_KEY }}
  REFRESH_TOKEN_PUBLIC_KEY: ${{ secrets.REFRESH_TOKEN_PUBLIC_KEY }}
  PASSWORD_RESET_TOKEN_PRIVATE_KEY: ${{ secrets.PASSWORD_RESET_TOKEN_PRIVATE_KEY }}
  PASSWORD_RESET_TOKEN_PUBLIC_KEY: ${{ secrets.PASSWORD_RESET_TOKEN_PUBLIC_KEY }}
  ACCOUNT_ACTIVATION_TOKEN_PRIVATE_KEY: ${{ secrets.ACCOUNT_ACTIVATION_TOKEN_PRIVATE_KEY }}
  ACCOUNT_ACTIVATION_TOKEN_PUBLIC_KEY: ${{ secrets.ACCOUNT_ACTIVATION_TOKEN_PUBLIC_KEY }}

jobs:
  jest-tests:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: lucella-test
        options: >- # Set health checks to wait until postgres has started
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.18.0
      - name: install yarn
        run: npm install --global yarn
      - name: docker ps -a
        run: docker ps -a
      - name: install dependencies
        run: yarn install
      - name: install typescript
        run: npm install -g typescript
      - name: compile typescript
        run: cd packages/common && tsc && echo compiled common directory && cd ../server && tsc && echo compiled server directory && cd ../..
      - name: install protoc
        run: sudo apt update && sudo apt install -y unzip && curl -Lo protoc.zip "https://github.com/protocolbuffers/protobuf/releases/download/v3.19.6/protoc-3.19.6-linux-x86_64.zip" && sudo unzip -q protoc.zip bin/protoc -d /usr/local && sudo chmod a+x /usr/local/bin/protoc && protoc --version
      - name: compile .proto files to js
        run: cd packages/common && yarn run compile-proto && cd ../..
      - name: docker ps
        run: docker ps
      - name: Run server tests and be done
        run: cd packages/server && yarn test --forceExit && echo completed
  cypress-run:
    runs-on: ubuntu-latest
    container:
      # image: cypress/browsers:node12.18.3-chrome87-ff82
      image: cypress/included:cypress-12.3.0-node-16.18.1-chrome-109.0.5414.74-1-ff-109.0-edge-109.0.1518.52-1
      options: --user root
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: lucella # note this is different than the lucella-test db used in the jest tests
        options: >- # Set health checks to wait until postgres has started
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      # - name: ownership
      #   run: sudo chown -R 1001:0 "/.npm"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          node-version: 16.18.0
      # - name: install yarn
      #   run: npm install --global yarn
      - name: install curl
        run: apt update && apt install curl
      - name: install protoc
        run: apt update && apt install -y unzip && curl -Lo protoc.zip "https://github.com/protocolbuffers/protobuf/releases/download/v3.19.6/protoc-3.19.6-linux-x86_64.zip" && unzip -q protoc.zip bin/protoc -d /usr/local && chmod a+x /usr/local/bin/protoc && protoc --version
      - name: install dependencies
        run: yarn install
      - name: install typescript
        run: npm install -g typescript
      - name: compile typescript
        run: cd packages/common && tsc && echo compiled common directory && cd ../server && tsc && echo compiled server directory && cd ../..
      - name: compile .proto files to js
        run: cd packages/common && yarn run compile-proto && cd ../..
      - name: run dev
        run: yarn dev 
#      - name: Cypress run
#        run: cd packages/client && yarn cypress run --browser chrome --headless
